[profile.release]
debug = true

[workspace]
members = [
  "cqueue",
  "des",
  "des_macros",
  "des_macros_core",
  "ndl",
  "examples",
]

[patch.crates-io]
tokio = {git = "https://github.com/PetrichorIT/tokio_sim", branch = "sim-core"}
