[profile.release]
debug = true

[workspace]
resolver = "2"
members = [
    "des",
    "des-cqueue",
    "des-macros",
    "des-macros-core",
    "des-ndl",
    "des-integration",
    "des-networks",
    "examples",
]
