[package]
edition = "2021"
name = "des-ndl"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unic-emoji-char = "0.9"
unicode-xid = "0.2"
termcolor = "*"