[package]
edition = "2021"
name = "des"
version = "0.2.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
internal-metrics = []
net = []
net-ipv6 = ["net"]
simtime-u128 = []
cqueue = []

[dependencies]
lazy_static = "1.4.0"
log = "0.4.14"
num-traits = "0.2"
rand = {version = "*", features = ["std_rng"]}
termcolor = "1.1.2"
unic-emoji-char = "0.9.0"
unicode-xid = "0.2.0"
calender_queue = { path = "../calender_queue" }

[dev-dependencies]
des_derive = {path = "../des_derive"}