[package]
edition = "2021"
name = "des"
version = "0.2.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
async = ["net", "dep:des_tokio"]
internal-metrics = []
net = ["dep:des_derive"]
net-ipv6 = ["net"]
# cqueue = [ "dep:cqueue" ]

[dependencies]
lazy_static = "1.4.0"
log = "0.4.14"
num-traits = "0.2"
rand = {version = "*", features = ["std_rng"]}
termcolor = "1.1.2"
unic-emoji-char = "0.9.0"
unicode-xid = "0.2.0"

cqueue = {path = "../cqueue", features = ["optimized"], optional = true}
des_derive = {path = "../des_derive", optional = true}
des_tokio = {path = "../des_tokio", optional = true}

[dev-dependencies]
futures = "0.3.21"
