[package]
name = "des"
#
# Other manifest items
#
authors = ["PetrichorIT <github.com/PetrichorIT>"]
categories = ["simulation", "asynchronous", "network-programming"]
description = """
A simulation backend for discrete event simulations, supporting
simulation of asynchronous systems via tokio.
"""
edition = "2021"
keywords = ["async", "simulation", "tokio", "net"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/PetrichorIT/des"
version = "0.3.2"

[features]
# Include nothing by default
default = []

# Include everything used for default test runs.
full = ["net", "cqueue", "async"]

async = ["net", "std-net", "dep:tokio", "dep:async-trait"]
async-sharedrt = ["async"]
cqueue = []
metrics = []
net = ["dep:des_macros"]
std-net = ["net"]

[dependencies]
# An internal logging impl can be very usefull. 
log = {version = "0.4.14"}
termcolor = "1.1.2"

# Rand primives must be set since they are bound to the
# runtime and sould be seedable by the user.
rand = {version = "*", features = ["std_rng"]}

sysinfo = "0.25"

# All other dependencies are optional
async-trait = {version = "0.1", optional = true}
des_macros = {path = "../des_macros", optional = true}
# tokio = {git = "https://github.com/PetrichorIT/tokio_sim", features = ["sim"], optional = true}
tokio = {path = "../../tokio_sim/tokio", features = ["sim"], optional = true}

[dev-dependencies]
futures = "0.3.21"
serial_test = "0.8.0"

[package.metadata.docs.rs]
all-features = true
