[package]
edition = "2021"
name = "des"
version = "0.3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
async = ["net", "dep:des_tokio"]
internal-metrics = []
net = ["dep:des_derive"]
net-ipv6 = ["net"]

[dependencies]
log = "0.4.14"
rand = {version = "*", features = ["std_rng"]}
termcolor = "1.1.2"

cqueue = {path = "../cqueue", features = ["optimized"], optional = true}
des_derive = {path = "../des_derive", optional = true}
des_tokio = {path = "../des_tokio", optional = true}

[dev-dependencies]
futures = "0.3.21"

[package.metadata.docs.rs]
all-features = true
