#![allow(missing_docs)]

use super::{HandleMessageEvent, MessageExitingConnection, Sim};
use crate::{
    net::{
        channel::SendError,
        gate::{Connection, GateRef},
        message::Message,
        module::{MOD_CTX, current},
        runtime::NetEvents,
    },
    prelude::{EventLifecycle, ModuleRef, RuntimeError},
    runtime::{LikeRuntimeError, Runtime},
    sync::Mutex,
    time::SimTime,
};

static EXEC_CTX: Mutex<EventExecutionContext> = Mutex::new(EventExecutionContext::new());

struct EventExecutionContext {
    // All new events that will be scheduled
    events: Vec<(NetEvents, SimTime)>,
    // errors
    error: Vec<Box<dyn LikeRuntimeError>>,
    // failure
    failure: Option<RuntimeError>,
    /// Indicates whether any call to the panic-hook has been observed. This should trigger a try-join to fast-find crashing tokio tasks.
    observed_panics: bool,
}

impl EventExecutionContext {
    const fn new() -> Self {
        Self {
            events: Vec::new(),
            error: Vec::new(),
            failure: None,
            observed_panics: false,
        }
    }
}

unsafe impl Send for EventExecutionContext {}
unsafe impl Sync for EventExecutionContext {}

impl ModuleRef {
    /// INTERNAL
    /// # Errors
    /// May occur
    #[allow(clippy::missing_panics_doc)]
    pub fn deactivate<A>(&self, rt: &mut Runtime<Sim<A>>) -> Result<(), RuntimeError>
    where
        A: EventLifecycle<Sim<A>>,
    {
        let mut ctx = EXEC_CTX.lock();
        let mut error = RuntimeError::empty();

        // (0) Check for panics in tokio threads
        #[cfg(feature = "async")]
        if ctx.observed_panics {
            use crate::net::processing::TokioRuntime;

            let mut processing = self.processing.try_borrow_mut().expect("failed to borrow");
            if let Some(err) = processing
                .downcast_element_mut::<TokioRuntime>()
                .and_then(|tokio| tokio.check_for_panics().err())
            {
                error.merge(err);
            }
            ctx.observed_panics = false;
        }

        // (1) Add events generated by this execution routine
        for (event, time) in ctx.events.drain(..) {
            rt.add_event(event, time);
        }

        // (2) Collect reported errors
        rt.app.error.extend(ctx.error.drain(..));

        // (3) Check for a critical failure
        error.merge(ctx.failure.take().unwrap_or_else(RuntimeError::empty));

        if error.is_empty() { Ok(()) } else { Err(error) }
    }
}

pub(crate) fn buf_init() {
    let mut ctx = EXEC_CTX.lock();
    ctx.events.clear();
    ctx.events.clear();
    ctx.observed_panics = false;
    ctx.failure = None;

    // TODO: remove ?
    // SAFTEY:
    // reseting the MOD_CTX is safe, since simulation lock is aquired.
    unsafe {
        MOD_CTX.reset(None);
    }
}

pub(crate) fn buf_report_panic() {
    let mut ctx = EXEC_CTX.lock();
    ctx.observed_panics = true;
}

pub(crate) fn buf_drop() {
    let mut ctx = EXEC_CTX.lock();
    *ctx = EventExecutionContext::new();
}

pub(crate) fn buf_send_at(
    msg: Message,
    gate: GateRef,
    send_time: SimTime,
) -> Result<(), SendError> {
    let mut ctx = EXEC_CTX.lock();

    // (0) If delayed send is active, dont skip gate_refs
    if send_time > SimTime::now() {
        ctx.events.push((
            NetEvents::MessageExitingConnection(MessageExitingConnection {
                con: Connection::new(gate),
                msg,
            }),
            send_time,
        ));
        return Ok(());
    }

    // (0) Else handle the event inlined, for instant effects on the associated
    // channels.
    let event = MessageExitingConnection {
        con: Connection::new(gate),
        msg,
    };
    event.handle_with_sink(&mut ctx.events)
}

pub(crate) fn buf_schedule_at(msg: Message, arrival_time: SimTime) {
    // continue to delay the delivery of event, since non other components are
    // used, and we dont block any channels. additionally this ensures that
    // timeouts are allways ordered later than packets, which is good
    let mut ctx = EXEC_CTX.lock();
    ctx.events.push((
        NetEvents::HandleMessageEvent(HandleMessageEvent {
            module: current().me(),
            message: msg,
        }),
        arrival_time,
    ));
}

pub(crate) fn buf_schedule_event(event: NetEvents, time: SimTime) {
    let mut ctx = EXEC_CTX.lock();
    ctx.events.push((event, time));
}

pub(crate) fn buf_report(e: impl LikeRuntimeError) {
    let mut ctx = EXEC_CTX.lock();
    ctx.error.push(Box::new(e));
}

pub(crate) fn buf_fail(e: RuntimeError) {
    let mut ctx = EXEC_CTX.lock();
    match &mut ctx.failure {
        None => ctx.failure = Some(e),
        Some(err) => err.merge(e),
    }
}
