use std::sync::Arc;

use des_sync_utils::Mutex;

use crate::{
    net::{
        Error, Sim,
        gate::Connection,
        runtime::{HandleMessageEvent, MessageExitingConnection, NetEvents, cfg::SimLifecycle},
    },
    prelude::{GateRef, Message, Runtime, SendError, current},
    time::SimTime,
};

#[derive(Debug, Default, Clone)]
pub(crate) struct EventExecutionContext {
    inner: Arc<Mutex<EventExecutionContextInner>>,
}

#[derive(Debug, Default)]
struct EventExecutionContextInner {
    // All new events that will be scheduled
    events: Vec<(NetEvents, SimTime)>,
    // errors
    errors: Vec<Error>,
    // failure
    failure: Option<Error>,
}

impl EventExecutionContext {
    pub(crate) fn report_error(&self, error: Error) {
        self.inner.lock().errors.push(error);
    }

    pub(crate) fn report_failure(&self, failure: Error) {
        let mut lock = self.inner.lock();
        match lock.failure {
            None => lock.failure = Some(Error::from(failure)),
            Some(ref mut existing_failure) => {
                existing_failure.append(failure);
            }
        }
    }

    pub(crate) fn send_in(
        &self,
        msg: Message,
        gate: GateRef,
        send_time: SimTime,
    ) -> Result<(), SendError> {
        let mut ctx = self.inner.lock();

        // (0) If delayed send is active, dont skip gate_refs
        if send_time > SimTime::now() {
            ctx.events.push((
                NetEvents::MessageExitingConnection(MessageExitingConnection {
                    con: Connection::new(gate),
                    msg,
                }),
                send_time,
            ));
            return Ok(());
        }

        // (0) Else handle the event inlined, for instant effects on the associated
        // channels.
        let event = MessageExitingConnection {
            con: Connection::new(gate),
            msg,
        };
        event.handle_with_sink(&mut ctx.events)
    }

    pub(crate) fn schedule(&self, message: Message, time: SimTime) {
        let event = NetEvents::HandleMessageEvent(HandleMessageEvent {
            module: current().me(),
            message,
        });
        self.schedule_event(event, time);
    }

    #[inline]
    pub(crate) fn schedule_event(&self, event: NetEvents, time: SimTime) {
        self.inner.lock().events.push((event, time));
    }
}

impl EventExecutionContext {
    pub(crate) fn finish<A: SimLifecycle>(self, rt: &mut Runtime<Sim<A>>) -> Result<(), Error> {
        let mut ctx = Arc::into_inner(self.inner)
            .expect("could not retrieve Arc")
            .into_inner();

        // (1) Add events generated by this execution routine
        for (event, time) in ctx.events.drain(..) {
            rt.add_event(event, time);
        }

        // (2) Collect reported errors
        rt.app.error.extend(ctx.errors.drain(..));

        // (3) Check for a critical failure
        match ctx.failure.take() {
            Some(errors) => Err(errors),
            None => Ok(()),
        }
    }
}
