use std::sync::Arc;

use des_sync_utils::Mutex;

use crate::{
    net::{
        Sim,
        gate::Connection,
        runtime::{HandleMessageEvent, MessageExitingConnection, NetEvents},
    },
    prelude::{EventLifecycle, GateRef, Message, Runtime, RuntimeError, SendError, current},
    runtime::LikeRuntimeError,
    time::SimTime,
};

#[derive(Debug, Default, Clone)]
pub(crate) struct EventExecutionContext {
    inner: Arc<Mutex<EventExecutionContextInner>>,
}

#[derive(Debug, Default)]
struct EventExecutionContextInner {
    // All new events that will be scheduled
    events: Vec<(NetEvents, SimTime)>,
    // errors
    error: Vec<Box<dyn LikeRuntimeError>>,
    // failure
    failure: Option<RuntimeError>,
}

impl EventExecutionContext {
    pub(crate) fn report_error(&self, error: Box<dyn LikeRuntimeError>) {
        self.inner.lock().error.push(error);
    }

    pub(crate) fn report_failure(&self, failure: RuntimeError) {
        let mut lock = self.inner.lock();
        match lock.failure {
            None => lock.failure = Some(failure),
            Some(ref mut existing_failure) => {
                existing_failure.merge(failure);
            }
        }
    }

    pub(crate) fn send_in(
        &self,
        msg: Message,
        gate: GateRef,
        send_time: SimTime,
    ) -> Result<(), SendError> {
        let mut ctx = self.inner.lock();

        // (0) If delayed send is active, dont skip gate_refs
        if send_time > SimTime::now() {
            ctx.events.push((
                NetEvents::MessageExitingConnection(MessageExitingConnection {
                    con: Connection::new(gate),
                    msg,
                }),
                send_time,
            ));
            return Ok(());
        }

        // (0) Else handle the event inlined, for instant effects on the associated
        // channels.
        let event = MessageExitingConnection {
            con: Connection::new(gate),
            msg,
        };
        event.handle_with_sink(&mut ctx.events)
    }

    pub(crate) fn schedule(&self, message: Message, time: SimTime) {
        let event = NetEvents::HandleMessageEvent(HandleMessageEvent {
            module: current().me(),
            message,
        });
        self.schedule_event(event, time);
    }

    #[inline]
    pub(crate) fn schedule_event(&self, event: NetEvents, time: SimTime) {
        self.inner.lock().events.push((event, time));
    }
}

impl EventExecutionContext {
    pub(crate) fn finish<A>(self, rt: &mut Runtime<Sim<A>>) -> Result<(), RuntimeError>
    where
        A: EventLifecycle<Sim<A>>,
    {
        let mut ctx = Arc::into_inner(self.inner)
            .expect("could not retrieve Arc")
            .into_inner();

        let mut error = RuntimeError::empty();

        // (0) Check for panics in tokio threads
        // #[cfg(feature = "async")]
        // if ctx.observed_panics {
        //     use crate::net::processing::TokioRuntime;

        //     let mut processing = self.processing.try_borrow_mut().expect("failed to borrow");
        //     if let Some(err) = processing
        //         .downcast_element_mut::<TokioRuntime>()
        //         .and_then(|tokio| tokio.check_for_panics().err())
        //     {
        //         error.merge(err);
        //     }
        //     ctx.observed_panics = false;
        // }

        // (1) Add events generated by this execution routine
        for (event, time) in ctx.events.drain(..) {
            rt.add_event(event, time);
        }

        // (2) Collect reported errors
        rt.app.error.extend(ctx.error.drain(..));

        // (3) Check for a critical failure
        error.merge(ctx.failure.take().unwrap_or_else(RuntimeError::empty));

        if error.is_empty() { Ok(()) } else { Err(error) }
    }
}
